### ISSUE TITLE
Jest: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by shaneog** [detrohutt/babel-plugin-inline-import-graphql-ast#89]
When testing using Jest, I receive the following error when running `babel.transform`. I am using the test code defined in the README of this plugin.
```js
import myImportedQuery from "./queries/productsQuery.graphql";
```

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

      at defaultResolve (node_modules/babel-plugin-import-graphql/build/requireGql.js:33:50)
      at PluginPass.exit (node_modules/babel-plugin-import-graphql/build/index.js:73:27)
      at newFn (node_modules/@babel/traverse/lib/visitors.js:177:21)
      at NodePath._call (node_modules/@babel/traverse/lib/path/context.js:53:20)
      at NodePath.call (node_modules/@babel/traverse/lib/path/context.js:40:17)
      at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:99:8)
      at TraversalContext.visitQueue (node_modules/@babel/traverse/lib/context.js:103:16)

```

I have put together the simplest possible reproduction of this here: https://github.com/shaneog/babel-transform-graphql-example

```sh
$ node --version
v14.18.1
$ npm --version
6.14.15
```

When Babel is run manually (`npx babel test/fixtures --out-dir dist`)  the code is transpiled correctly _(formatted for ease of viewing)_:

<details>
  <summary>Click to see the formatted, transpiled JS</summary>

```js
var myImportedQuery = {
  kind: "Document",
  definitions: [
    {
      kind: "OperationDefinition",
      operation: "query",
      name: { kind: "Name", value: "products" },
      variableDefinitions: [],
      directives: [],
      selectionSet: {
        kind: "SelectionSet",
        selections: [
          {
            kind: "Field",
            name: { kind: "Name", value: "products" },
            arguments: [],
            directives: [],
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                {
                  kind: "Field",
                  name: { kind: "Name", value: "productId" },
                  arguments: [],
                  directives: [],
                },
                {
                  kind: "FragmentSpread",
                  name: { kind: "Name", value: "productFragment" },
                  directives: [],
                },
              ],
            },
          },
        ],
      },
    },
    {
      kind: "FragmentDefinition",
      name: { kind: "Name", value: "productFragment" },
      typeCondition: {
        kind: "NamedType",
        name: { kind: "Name", value: "Product" },
      },
      directives: [],
      selectionSet: {
        kind: "SelectionSet",
        selections: [
          {
            kind: "Field",
            name: { kind: "Name", value: "name" },
            arguments: [],
            directives: [],
          },
          {
            kind: "Field",
            name: { kind: "Name", value: "description" },
            arguments: [],
            directives: [],
          },
          {
            kind: "Field",
            name: { kind: "Name", value: "weight" },
            arguments: [],
            directives: [],
          },
        ],
      },
    },
  ],
  loc: {
    start: 0,
    end: 109,
    source: {
      body: '#import "./productFragment.graphql"\nquery products {\n  products {\n    productId\n    ...productFragment\n  }\n}\n',
      name: "GraphQL request",
      locationOffset: { line: 1, column: 1 },
    },
  },
};

```
</details>

This bug seems to be similar to #79.

**Comment by punksta** [comment]
I am getting similar issue after upgrading react-native to 0.69.5 and babel "^7.18.6",
